#!/bin/sh
# Build the Cocoon PWA into web/.
#
# Unlike the old Cogent Core build, there is no framework to bundle: this
# compiles the pure winding core (internal/wind) to wasm, copies Go's runtime
# shim next to it, and stamps a content hash into the service worker so a new
# deploy invalidates exactly the files that changed and nothing else.
#
# The service worker is GENERATED here rather than hand-maintained, because
# its cache name must track the build. Do not edit web/sw.js by hand.
set -e

ROOT=$(cd "$(dirname "$0")/.." && pwd)
WEB="$ROOT/web"

echo "==> building wasm core"
cd "$ROOT"
GOOS=js GOARCH=wasm go build -ldflags="-s -w" -o "$WEB/cocoon.wasm" ./cmd/wasm

echo "==> copying Go wasm runtime shim"
GOROOT=$(go env GOROOT)
if [ -f "$GOROOT/lib/wasm/wasm_exec.js" ]; then
  cp "$GOROOT/lib/wasm/wasm_exec.js" "$WEB/wasm_exec.js"
else
  cp "$GOROOT/misc/wasm/wasm_exec.js" "$WEB/wasm_exec.js"
fi

echo "==> syncing profiles and sample winds"
mkdir -p "$WEB/profiles" "$WEB/winds"
cp "$ROOT"/profiles/*.csv "$WEB/profiles/" 2>/dev/null || true
cp "$ROOT"/winds/*.json "$WEB/winds/" 2>/dev/null || true

# Hash every asset the service worker precaches. Any change to any of them
# produces a new cache name, so the worker updates; if nothing changed the
# hash is identical, no new worker installs, and nothing is re-downloaded.
echo "==> generating service worker"
cd "$WEB"
ASSETS="index.html manifest.webmanifest cocoon.wasm wasm_exec.js
css/app.css
js/app.js js/model.js js/blocks.js js/viewer.js js/wasm.js js/store.js
vendor/three.module.min.js vendor/OrbitControls.js
icons/icon.svg"

HASH=$(cat $ASSETS 2>/dev/null | sha1sum | cut -c1-12)

{
  echo "// GENERATED by scripts/build-web.sh -- do not edit."
  echo "// Cache name embeds a hash of every precached asset, so an unchanged"
  echo "// build produces an identical worker and triggers no update at all."
  echo "const CACHE = 'cocoon-$HASH';"
  echo "const ASSETS = ["
  for a in $ASSETS; do echo "  './$a',"; done
  echo "];"
  cat <<'EOF'

self.addEventListener('install', (e) => {
  // Precache with cache:'reload' rather than cache.addAll().
  //
  // addAll() goes through the browser's HTTP cache, so if a stale copy of an
  // asset is still considered fresh it gets copied straight into the service
  // worker cache -- and then served indefinitely, because the SW is
  // cache-first. That is a stale deploy that survives a hard reload. Servers
  // without explicit Cache-Control headers (python -m http.server, and plenty
  // of static hosts) make this easy to hit, because browsers then apply
  // heuristic freshness.
  //
  // cache:'reload' forces a network fetch, so the SW caches what the server
  // actually has right now.
  //
  // skipWaiting + clients.claim (below) then get that build to open pages on
  // the next reload rather than the one after that.
  e.waitUntil(
    caches.open(CACHE).then((c) =>
      Promise.all(ASSETS.map((a) =>
        fetch(a, { cache: 'reload' }).then((r) => {
          if (!r.ok) throw new Error('precache failed: ' + a + ' (' + r.status + ')');
          return c.put(a, r);
        })
      ))
    ).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  // Cache-first is safe here because the cache name is content-hashed: a new
  // deploy means a new cache, and the old one is deleted on activate.
  e.respondWith(
    caches.match(e.request).then((hit) => hit || fetch(e.request))
  );
});
EOF
} > sw.js

echo "==> done"
ls -l "$WEB/cocoon.wasm" | awk '{printf "    cocoon.wasm  %.1f MB\n", $5/1048576}'
gzip -9 -c "$WEB/cocoon.wasm" | wc -c | awk '{printf "    gzipped      %.2f MB\n", $1/1048576}'
echo "    cache        cocoon-$HASH"
echo
echo "Serve with:  python3 -m http.server 8080 --directory web"
